/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Appointment {
  'id' : bigint,
  'status' : AppointmentStatus,
  'doctorId' : bigint,
  'patientId' : Uint8Array,
  'createdAt' : Time,
  'timeSlot' : TimeSlot,
}
export interface AppointmentInput { 'doctorId' : bigint, 'timeSlot' : TimeSlot }
export type AppointmentStatus = { 'cancelled' : null } |
  { 'rescheduled' : null } |
  { 'booked' : null };
export interface DoctorProfile {
  'id' : bigint,
  'name' : string,
  'experienceYears' : bigint,
  'availableSlots' : Array<TimeSlot>,
  'specialization' : Specialization,
  'hospitalName' : string,
}
export interface PatientProfile {
  'id' : Uint8Array,
  'name' : string,
  'email' : string,
  'phoneNumber' : string,
}
export type Specialization = { 'ophthalmology' : null } |
  { 'cardiology' : null } |
  { 'internalMedicine' : null } |
  { 'generalPractice' : null } |
  { 'orthopedics' : null } |
  { 'pediatrics' : null } |
  { 'dermatology' : null } |
  { 'generalSpecialist' : null } |
  { 'gynecology' : null } |
  { 'dentistry' : null } |
  { 'neurology' : null };
export type Time = bigint;
export interface TimeSlot {
  'day' : string,
  'startTime' : string,
  'endTime' : string,
}
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserProfileInput {
  'name' : string,
  'email' : string,
  'phoneNumber' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'askMedicalChatbot' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'bookAppointment' : ActorMethod<[AppointmentInput, Uint8Array], bigint>,
  'cancelAppointment' : ActorMethod<[bigint, Uint8Array], undefined>,
  'createPatientProfile' : ActorMethod<
    [string, string, string, Uint8Array],
    undefined
  >,
  'getAllDoctors' : ActorMethod<[], Array<DoctorProfile>>,
  'getCallerPatientProfile' : ActorMethod<[Uint8Array], PatientProfile>,
  'getCallerUserProfile' : ActorMethod<[Uint8Array], [] | [PatientProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDoctorAvailability' : ActorMethod<[bigint], Array<TimeSlot>>,
  'getDoctorById' : ActorMethod<[bigint], DoctorProfile>,
  'getPatientAppointments' : ActorMethod<[Uint8Array], Array<Appointment>>,
  'getPatientProfile' : ActorMethod<[Uint8Array], PatientProfile>,
  'getUserProfile' : ActorMethod<[Uint8Array], [] | [PatientProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rescheduleAppointment' : ActorMethod<
    [bigint, TimeSlot, Uint8Array],
    undefined
  >,
  'runScheduledNotifications' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [UserProfileInput, Uint8Array],
    undefined
  >,
  'system_install_was' : ActorMethod<[], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updatePatientProfile' : ActorMethod<
    [string, string, string, Uint8Array],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];