/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const TimeSlot = IDL.Record({
  'day' : IDL.Text,
  'startTime' : IDL.Text,
  'endTime' : IDL.Text,
});
export const AppointmentInput = IDL.Record({
  'doctorId' : IDL.Nat,
  'timeSlot' : TimeSlot,
});
export const Specialization = IDL.Variant({
  'ophthalmology' : IDL.Null,
  'cardiology' : IDL.Null,
  'internalMedicine' : IDL.Null,
  'generalPractice' : IDL.Null,
  'orthopedics' : IDL.Null,
  'pediatrics' : IDL.Null,
  'dermatology' : IDL.Null,
  'generalSpecialist' : IDL.Null,
  'gynecology' : IDL.Null,
  'dentistry' : IDL.Null,
  'neurology' : IDL.Null,
});
export const DoctorProfile = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'availableSlots' : IDL.Vec(TimeSlot),
  'specialization' : Specialization,
  'hospitalName' : IDL.Text,
});
export const PatientProfile = IDL.Record({
  'id' : IDL.Vec(IDL.Nat8),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const AppointmentStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'rescheduled' : IDL.Null,
  'booked' : IDL.Null,
});
export const Time = IDL.Int;
export const Appointment = IDL.Record({
  'id' : IDL.Nat,
  'status' : AppointmentStatus,
  'doctorId' : IDL.Nat,
  'patientId' : IDL.Vec(IDL.Nat8),
  'createdAt' : Time,
  'timeSlot' : TimeSlot,
});
export const UserProfileInput = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'askMedicalChatbot' : IDL.Func([IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'bookAppointment' : IDL.Func(
      [AppointmentInput, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
  'cancelAppointment' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [], []),
  'createPatientProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'getAllDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
  'getCallerPatientProfile' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [PatientProfile],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDoctorAvailability' : IDL.Func([IDL.Nat], [IDL.Vec(TimeSlot)], ['query']),
  'getDoctorById' : IDL.Func([IDL.Nat], [DoctorProfile], ['query']),
  'getPatientAppointments' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Vec(Appointment)],
      ['query'],
    ),
  'getPatientProfile' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [PatientProfile],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Opt(PatientProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rescheduleAppointment' : IDL.Func(
      [IDL.Nat, TimeSlot, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'runScheduledNotifications' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func(
      [UserProfileInput, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
  'system_install_was' : IDL.Func([], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updatePatientProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const TimeSlot = IDL.Record({
    'day' : IDL.Text,
    'startTime' : IDL.Text,
    'endTime' : IDL.Text,
  });
  const AppointmentInput = IDL.Record({
    'doctorId' : IDL.Nat,
    'timeSlot' : TimeSlot,
  });
  const Specialization = IDL.Variant({
    'ophthalmology' : IDL.Null,
    'cardiology' : IDL.Null,
    'internalMedicine' : IDL.Null,
    'generalPractice' : IDL.Null,
    'orthopedics' : IDL.Null,
    'pediatrics' : IDL.Null,
    'dermatology' : IDL.Null,
    'generalSpecialist' : IDL.Null,
    'gynecology' : IDL.Null,
    'dentistry' : IDL.Null,
    'neurology' : IDL.Null,
  });
  const DoctorProfile = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'availableSlots' : IDL.Vec(TimeSlot),
    'specialization' : Specialization,
    'hospitalName' : IDL.Text,
  });
  const PatientProfile = IDL.Record({
    'id' : IDL.Vec(IDL.Nat8),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const AppointmentStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'rescheduled' : IDL.Null,
    'booked' : IDL.Null,
  });
  const Time = IDL.Int;
  const Appointment = IDL.Record({
    'id' : IDL.Nat,
    'status' : AppointmentStatus,
    'doctorId' : IDL.Nat,
    'patientId' : IDL.Vec(IDL.Nat8),
    'createdAt' : Time,
    'timeSlot' : TimeSlot,
  });
  const UserProfileInput = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'askMedicalChatbot' : IDL.Func([IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'bookAppointment' : IDL.Func(
        [AppointmentInput, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
    'cancelAppointment' : IDL.Func([IDL.Nat, IDL.Vec(IDL.Nat8)], [], []),
    'createPatientProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'getAllDoctors' : IDL.Func([], [IDL.Vec(DoctorProfile)], ['query']),
    'getCallerPatientProfile' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [PatientProfile],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDoctorAvailability' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(TimeSlot)],
        ['query'],
      ),
    'getDoctorById' : IDL.Func([IDL.Nat], [DoctorProfile], ['query']),
    'getPatientAppointments' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Vec(Appointment)],
        ['query'],
      ),
    'getPatientProfile' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [PatientProfile],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Opt(PatientProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rescheduleAppointment' : IDL.Func(
        [IDL.Nat, TimeSlot, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'runScheduledNotifications' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [UserProfileInput, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
    'system_install_was' : IDL.Func([], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updatePatientProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Nat8)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };