/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TimeSlot {
    day: string;
    startTime: string;
    endTime: string;
}
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export type Time = bigint;
export interface DoctorProfile {
    id: bigint;
    name: string;
    experienceYears: bigint;
    availableSlots: Array<TimeSlot>;
    specialization: Specialization;
    hospitalName: string;
}
export interface AppointmentInput {
    doctorId: bigint;
    timeSlot: TimeSlot;
}
export interface http_header {
    value: string;
    name: string;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface PatientProfile {
    id: Principal;
    name: string;
    email: string;
    phoneNumber: string;
}
export interface Appointment {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    createdAt: Time;
    timeSlot: TimeSlot;
}
export interface UserProfileInput {
    name: string;
    email: string;
    phoneNumber: string;
}
export enum AppointmentStatus {
    cancelled = "cancelled",
    rescheduled = "rescheduled",
    booked = "booked"
}
export enum Specialization {
    ophthalmology = "ophthalmology",
    cardiology = "cardiology",
    internalMedicine = "internalMedicine",
    generalPractice = "generalPractice",
    orthopedics = "orthopedics",
    pediatrics = "pediatrics",
    dermatology = "dermatology",
    generalSpecialist = "generalSpecialist",
    gynecology = "gynecology",
    neurology = "neurology"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    askMedicalChatbot(question: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    bookAppointment(appointmentInput: AppointmentInput): Promise<bigint>;
    cancelAppointment(appointmentId: bigint): Promise<void>;
    createPatientProfile(name: string, phoneNumber: string, email: string): Promise<void>;
    getAllDoctors(): Promise<Array<DoctorProfile>>;
    getCallerPatientProfile(): Promise<PatientProfile>;
    getCallerUserProfile(): Promise<PatientProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDoctorAvailability(doctorId: bigint): Promise<Array<TimeSlot>>;
    getDoctorById(doctorId: bigint): Promise<DoctorProfile>;
    getPatientAppointments(): Promise<Array<Appointment>>;
    getPatientProfile(user: Principal): Promise<PatientProfile>;
    getUserProfile(user: Principal): Promise<PatientProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rescheduleAppointment(appointmentId: bigint, newTimeSlot: TimeSlot): Promise<void>;
    runScheduledNotifications(): Promise<void>;
    saveCallerUserProfile(profile: UserProfileInput): Promise<void>;
    system_install_was(): Promise<void>;
    transform(input: TransformationInput): Promise<TransformationOutput>;
    updatePatientProfile(name: string, phoneNumber: string, email: string): Promise<void>;
}
import type { Appointment as _Appointment, AppointmentStatus as _AppointmentStatus, DoctorProfile as _DoctorProfile, PatientProfile as _PatientProfile, Specialization as _Specialization, Time as _Time, TimeSlot as _TimeSlot, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async askMedicalChatbot(arg0: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.askMedicalChatbot(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.askMedicalChatbot(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async bookAppointment(arg0: AppointmentInput): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.bookAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bookAppointment(arg0);
            return result;
        }
    }
    async cancelAppointment(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelAppointment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelAppointment(arg0);
            return result;
        }
    }
    async createPatientProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createPatientProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPatientProfile(arg0, arg1, arg2);
            return result;
        }
    }
    async getAllDoctors(): Promise<Array<DoctorProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDoctors();
                return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDoctors();
            return from_candid_vec_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerPatientProfile(): Promise<PatientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerPatientProfile();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerPatientProfile();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDoctorAvailability(arg0: bigint): Promise<Array<TimeSlot>> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorAvailability(arg0);
            return result;
        }
    }
    async getDoctorById(arg0: bigint): Promise<DoctorProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getDoctorById(arg0);
                return from_candid_DoctorProfile_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDoctorById(arg0);
            return from_candid_DoctorProfile_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientAppointments(): Promise<Array<Appointment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientAppointments();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientAppointments();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPatientProfile(arg0: Principal): Promise<PatientProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getPatientProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPatientProfile(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<PatientProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rescheduleAppointment(arg0: bigint, arg1: TimeSlot): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rescheduleAppointment(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rescheduleAppointment(arg0, arg1);
            return result;
        }
    }
    async runScheduledNotifications(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.runScheduledNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.runScheduledNotifications();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfileInput): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async system_install_was(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.system_install_was();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.system_install_was();
            return result;
        }
    }
    async transform(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transform(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transform(arg0);
            return result;
        }
    }
    async updatePatientProfile(arg0: string, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePatientProfile(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePatientProfile(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_AppointmentStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AppointmentStatus): AppointmentStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Appointment_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Appointment): Appointment {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_DoctorProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DoctorProfile): DoctorProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Specialization_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Specialization): Specialization {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PatientProfile]): PatientProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    createdAt: _Time;
    timeSlot: _TimeSlot;
}): {
    id: bigint;
    status: AppointmentStatus;
    doctorId: bigint;
    patientId: Principal;
    createdAt: Time;
    timeSlot: TimeSlot;
} {
    return {
        id: value.id,
        status: from_candid_AppointmentStatus_n14(_uploadFile, _downloadFile, value.status),
        doctorId: value.doctorId,
        patientId: value.patientId,
        createdAt: value.createdAt,
        timeSlot: value.timeSlot
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    name: string;
    experienceYears: bigint;
    availableSlots: Array<_TimeSlot>;
    specialization: _Specialization;
    hospitalName: string;
}): {
    id: bigint;
    name: string;
    experienceYears: bigint;
    availableSlots: Array<TimeSlot>;
    specialization: Specialization;
    hospitalName: string;
} {
    return {
        id: value.id,
        name: value.name,
        experienceYears: value.experienceYears,
        availableSlots: value.availableSlots,
        specialization: from_candid_Specialization_n6(_uploadFile, _downloadFile, value.specialization),
        hospitalName: value.hospitalName
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    rescheduled: null;
} | {
    booked: null;
}): AppointmentStatus {
    return "cancelled" in value ? AppointmentStatus.cancelled : "rescheduled" in value ? AppointmentStatus.rescheduled : "booked" in value ? AppointmentStatus.booked : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ophthalmology: null;
} | {
    cardiology: null;
} | {
    internalMedicine: null;
} | {
    generalPractice: null;
} | {
    orthopedics: null;
} | {
    pediatrics: null;
} | {
    dermatology: null;
} | {
    generalSpecialist: null;
} | {
    gynecology: null;
} | {
    neurology: null;
}): Specialization {
    return "ophthalmology" in value ? Specialization.ophthalmology : "cardiology" in value ? Specialization.cardiology : "internalMedicine" in value ? Specialization.internalMedicine : "generalPractice" in value ? Specialization.generalPractice : "orthopedics" in value ? Specialization.orthopedics : "pediatrics" in value ? Specialization.pediatrics : "dermatology" in value ? Specialization.dermatology : "generalSpecialist" in value ? Specialization.generalSpecialist : "gynecology" in value ? Specialization.gynecology : "neurology" in value ? Specialization.neurology : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Appointment>): Array<Appointment> {
    return value.map((x)=>from_candid_Appointment_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DoctorProfile>): Array<DoctorProfile> {
    return value.map((x)=>from_candid_DoctorProfile_n4(_uploadFile, _downloadFile, x));
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
